# Generated by Django 5.1.3 on 2025-07-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_full_name_userprofile_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='fullname',
            new_name='fullName',
        ),
    ]
