# Generated by Django 5.1.3 on 2025-07-19 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultantprofile',
            name='experience_years',
        ),
    ]
