# Generated by Django 5.1.3 on 2025-07-22 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0003_rename_end_time_availabletime_endtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultantprofile',
            name='isActive',
        ),
    ]
