# Generated by Django 5.1.3 on 2025-07-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0004_remove_consultantprofile_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
