# Generated by Django 5.1.3 on 2025-07-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('consultant', '0003_rename_end_time_availabletime_endtime_and_more'),
        ('users', '0003_rename_fullname_userprofile_fullname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='Appointmnet',
        ),
        migrations.RenameField(
            model_name='appointmnet',
            old_name='available_time',
            new_name='availableTime',
        ),
        migrations.RenameField(
            model_name='appointmnet',
            old_name='booked_at',
            new_name='bookedAt',
        ),
    ]
