# Generated by Django 5.1.3 on 2025-07-21 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_rename_session_appointmnet_and_more'),
        ('consultant', '0003_rename_end_time_availabletime_endtime_and_more'),
        ('users', '0003_rename_fullname_userprofile_fullname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointmnet',
            new_name='Appointment',
        ),
    ]
